core/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from core.views import HomeView, EveryDayReportView, EveryWeekReportView, Results, AdminReview, Success, AboutPage, \
    AdminResultView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('everydayreport/', login_required(EveryDayReportView.as_view()), name='everydayreport'),
    path('everyweekreport/', login_required(EveryWeekReportView.as_view()), name='everyweekreport'),
    path('results/', login_required(Results.as_view()), name='results'),
    path('adminviewresults/<pk>/', login_required(AdminResultView.as_view()), name='results'),
    path('adminreview/', login_required(AdminReview.as_view()), name='admin_review'),
    path('success/', Success.as_view(), name='success'),
    path('about/', AboutPage.as_view(), name='about'),
]

fitnesstreker/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from fitnesstreker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls", namespace="users")),
    path('', include("core.urls", namespace="core")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import SignUp, ProfileUpdate, ProfileCreate

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),
    path('profilecreate/', login_required(ProfileCreate.as_view()), name='profile_create'),
    path('profileupdate/', login_required(ProfileUpdate.as_view()), name='profile_update'),
]

core/models.py
from math import log

from ckeditor.fields import RichTextField
from django.db import models
from users.forms import User
from datetime import date

from users.models import Profile


class EveryDayReport(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Участник')
    date = models.DateField(default=date.today, verbose_name='Дата отчета')
    weight = models.FloatField(verbose_name='Вес утром')
    steps = models.IntegerField(verbose_name='Шаги')
    critical_days = models.BooleanField(default=False, verbose_name='Критические дни')
    link = models.CharField(max_length=250, default='ссылка', blank=True, verbose_name='Ссылка на отчет')
    file = models.FileField(upload_to='user_file', blank=True, verbose_name='Файл отчета')

    def __str__(self):
        return f'{self.user.profile.name} | отчет от {self.date}'

    class Meta:
        verbose_name = 'Ежедневные отчеты'
        verbose_name_plural = 'Ежедневный отчет'


class EveryWeekReport(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Участник')
    date = models.DateField(default=date.today, verbose_name='Дата отчета')
    weight = models.FloatField(verbose_name='Вес')
    neck = models.FloatField(verbose_name='Шея')
    waist = models.FloatField(verbose_name='Бедра')
    hips = models.FloatField(verbose_name='Талия')
    side_view = models.ImageField(upload_to='user_photo', blank=True, verbose_name='Вид сбоку')
    front_view = models.ImageField(upload_to='user_photo', blank=True, verbose_name='Вид спереди')
    back_view = models.ImageField(upload_to='user_photo', blank=True, verbose_name='Вид сзади')

    @property
    def fat(self):
        if self.user.gender == 'men':
            fat = 495 / (1.0324 - 0.19077 * log(self.hips - self.neck, 10) + 0.15456 * log(self.user.growth, 10)) - 450
        else:
            fat = 495 / (1.29579 - 0.35004 * log(self.hips + self.waist - self.neck, 10) + 0.22100 * log(self.user.growth, 10)) - 450
        return f'{fat:.{2}f}'

    def __str__(self):
        return f'Отчет от {self.user} дата {self.date}'

    class Meta:
        verbose_name = 'Еженедельные отчеты'
        verbose_name_plural = 'Еженедельный отчет'



class Page(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название страницы')
    slug = models.SlugField(unique=True, verbose_name='URL')
    text = RichTextField('Содержание', blank=True)
    image = models.ImageField(upload_to='author', blank=True, verbose_name='Изображение автора')

    class Meta:
        verbose_name = 'Страницу'
        verbose_name_plural = 'Страницы'

    def __str__(self):
        return self.title


class PageImage(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE, verbose_name='Страница')
    image_before = models.ImageField(upload_to='reviews', blank=True, verbose_name='Фото')

    class Meta:
        verbose_name = 'Фото отзыв'
        verbose_name_plural = 'Фото отзывы'


class Review(models.Model):
    name = models.CharField(max_length=100, verbose_name='ФИО')
    text = models.TextField('Отзыв')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

core/forms.py
from django import forms
from core.models import EveryDayReport, EveryWeekReport


class EveryDayReportForm(forms.ModelForm):
    class Meta:
        model = EveryDayReport
        fields = ['date', 'weight', 'steps', 'critical_days', 'link', 'file']
        widgets = {
            'date': forms.DateInput(format = '%Y-%m-%d',attrs={'type': 'date'})
        }


class EveryWeekReportForm(forms.ModelForm):
    class Meta:
        model = EveryWeekReport
        fields = ['date', 'weight', 'neck', 'waist', 'hips', 'side_view', 'back_view', 'front_view']
        widgets = {
            'date': forms.DateInput(format = '%Y-%m-%d',attrs={'type': 'date'})
        }

core/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db.models import Avg, Min
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, DetailView

from core.forms import EveryDayReportForm, EveryWeekReportForm
from core.models import EveryWeekReport, Page, Review
from tasks.models import Task, Plank
from users.forms import User


def active_check(user):
    return user.active


class HomeView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['page'] = Page.objects.get(slug='about')
        context['reviews'] = Review.objects.all()
        return context


class AboutPage(DetailView):
    template_name = 'core/about.html'
    model = Page

    def get_object(self, queryset=None):
        return Page.objects.get(slug='about')


class EveryDayReportView(UserPassesTestMixin, TemplateView):
    template_name = 'core/everydayreport.html'
    form_class = EveryDayReportForm()
    success_url = '/'

    def test_func(self):
        if self.request.user.profile and self.request.user.profile.active:
            return True
        else:
            return False

    def handle_no_permission(self):
        return redirect('core:home')

    def get_context_data(self, **kwargs):
        context = super(EveryDayReportView,self).get_context_data(**kwargs)
        context['form'] = EveryDayReportForm
        return context

    def post(self, request):
        form = EveryDayReportForm(request.POST, request.FILES)
        if form.is_valid():
            report = form.save(commit=False)
            report.user = request.user
            report.save()
            return redirect('core:success')

        context = {'form': form}
        return render(request, self.template_name, context)


class EveryWeekReportView(UserPassesTestMixin, TemplateView):
    template_name = 'core/everyweekreport.html'
    form_class = EveryWeekReportForm()
    success_url = '/'

    def test_func(self):
        if self.request.user.profile and self.request.user.profile.active:
            return True
        else:
            return False

    def handle_no_permission(self):
        return redirect('core:home')

    def get_context_data(self, **kwargs):
        context = super(EveryWeekReportView,self).get_context_data(**kwargs)
        context['form'] = EveryWeekReportForm
        return context

    def post(self, request):
        form = EveryWeekReportForm(request.POST, request.FILES)
        if form.is_valid():
            report = form.save(commit=False)
            report.user = request.user.profile
            report.save()
            return redirect('core:success')

        context = {'form': form}
        return render(request, self.template_name, context)


class Results(UserPassesTestMixin, TemplateView):
    template_name = 'core/results.html'

    def test_func(self):
        if self.request.user.profile and self.request.user.profile.active:
            return True
        else:
            return False

    def handle_no_permission(self):
        return redirect('core:home')

    def get_context_data(self, **kwargs):
        context = super(Results, self).get_context_data(**kwargs)
        user = User.objects.get(username=self.request.user)
        everyweekreports = EveryWeekReport.objects.filter(user=user.profile)
        context['weight_average'] = everyweekreports.aggregate(average=Avg('weight'))
        context['weight_min'] = everyweekreports.aggregate(min=Min('weight'))
        context['report_list'] = everyweekreports.order_by('-date')
        if everyweekreports.count() > 1:
            context['report_previous'] = everyweekreports.order_by('-id')[1]
        context['report_last'] = everyweekreports.last()
        try:
            if everyweekreports.order_by('-id')[1]:
                context['you_today_result_weight'] = everyweekreports.last().weight - everyweekreports.first().weight
                context['you_today_result_neck'] = everyweekreports.last().neck - everyweekreports.first().neck
                context['you_today_result_waist'] = everyweekreports.last().waist - everyweekreports.first().waist
                context['you_today_result_hips'] = everyweekreports.last().hips - everyweekreports.first().hips
                context['you_today_result_fat'] = float(everyweekreports.last().fat) - float(everyweekreports.first().fat)
        finally:
            return context
        return context


class AdminReview(UserPassesTestMixin, TemplateView):
    template_name = 'core/adminreview.html'

    def test_func(self):
        if self.request.user.profile and self.request.user.profile.active:
            return True
        else:
            return False

    def handle_no_permission(self):
        return redirect('core:home')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = Task.objects.filter(profile=self.request.user.profile).last()
        context['planks'] = Plank.objects.filter(profile__user=self.request.user)
        return context


class Success(TemplateView):
    template_name = 'core/success.html'


class AdminResultView(UserPassesTestMixin, TemplateView):
    template_name = 'core/admin_results.html'

    def test_func(self):
        if self.request.user.profile and self.request.user.profile.active:
            return True
        else:
            return False

    def handle_no_permission(self):
        return redirect('core:home')

    def get_context_data(self, **kwargs):
        context = super(AdminResultView, self).get_context_data(**kwargs)
        user = User.objects.get(username=self.request.user)
        everyweekreports = EveryWeekReport.objects.filter(user_id=kwargs['pk'])
        context['weight_average'] = everyweekreports.aggregate(average=Avg('weight'))
        context['weight_min'] = everyweekreports.aggregate(min=Min('weight'))
        context['report_list'] = everyweekreports.order_by('-date')
        if everyweekreports.count() > 1:
            context['report_previous'] = everyweekreports.order_by('-id')[1]
        context['report_last'] = everyweekreports.last()
        try:
            if everyweekreports.order_by('-id')[1]:
                context['you_today_result_weight'] = everyweekreports.last().weight - everyweekreports.first().weight
                context['you_today_result_neck'] = everyweekreports.last().neck - everyweekreports.first().neck
                context['you_today_result_waist'] = everyweekreports.last().waist - everyweekreports.first().waist
                context['you_today_result_hips'] = everyweekreports.last().hips - everyweekreports.first().hips
                context['you_today_result_fat'] = float(everyweekreports.last().fat) - float(everyweekreports.first().fat)

        finally:
            return context
        return context

templates/core/about.html
{% extends 'base.html' %}

{% block content %}
    <body class="page-account">
    <input type="checkbox" id="hamb"/>
    <header>
        {% include 'includes/nav.html' %}
    </header>
    <main>
        <section class="about">
            <div class="about-author">
                <img src="{{ object.image.url }}" alt="Фото автора">
            </div>
            <div>{{ object.text|safe }}</div>
        </section>
    </main>
    </body>
{% endblock %}

templates/core/adminreview.html
{% extends 'base.html' %}

{% block content %}
    <body class="page-account">
    <input type="checkbox" id="hamb"/>
    {% include 'includes/header.html' %}
    <main>
        <section class="account sent">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">
                            {{ message|safe }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
            <h3>Здесь будут задания от тренера.</h3>
            {% for plank in planks %}
                <div class="table1">
                    <p class="table1-title">Планка </p>
                    <div class="table1-content">
                        <div class="t1-row">
                            <div class="t1-cell-th1">Дней</div>
                            <div class="t1-cell-th2">Калорий</div>
                            <div class="t1-cell-th3">Белок</div>
                            <div class="t1-cell-th4">Шаги</div>
                        </div>
                        <div class="t2-row">
                            <div class="t2-cell-th1">{{ plank.days }}</div>
                            <div class="t2-cell-th2">{{ plank.callories }}</div>
                            <div class="t2-cell-th3">{{ plank.protein }}</div>
                            <div class="t2-cell-th4">{{ plank.steps }}</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="not">
                <p class="not-title">Задание на неделю</p>
                <p class="not-content">
                    {{ tasks.text|safe }}
                </p>
            </div>
            <a href="{% url 'core:results' %}" class="btn">
                <span>Мой результат</span>
            </a>
        </section>
    </main>
    </body>
{% endblock %}

templates/core/everydayreport.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body class="page-account">
    <input type="checkbox" id="hamb"/>
    {% include 'includes/header.html' %}
    <main>
        <section class="account">
            <h1>Ежедневный отчет</h1>
            <form class="account-form" method="post" enctype="multipart/form-data" action="{% url 'core:everydayreport' %}">
                {% csrf_token %}
                <div class="account-field">
                    <label for="date">Дата</label>
                    {{ form.date }}
                </div>
                <div class="account-field">
                    <label for="weight">Вес утром</label>
                    <input type="number" name="weight" id="weight" step="0.1" min="0" required/>
                </div>
                <div class="account-field">
                    <label for="step">Шаги</label>
                    <input type="number" name="steps" id="step" step="0.1" min="0" required/>
                </div>
                <div class="account-field">
                    <label for="food">Ссылка на отчет</label>
                    <input type="text" name="link" id="id_link"/>
                </div>
                <div class="account-field">
                    <label for="food">Файл</label>
                    {{ form.file }}
                </div>
                <div class="account-field">
                    <input type="checkbox" name="critical_days" id="kd"/>
                    <label for="kd">
                        <span>КД</span>
                        <span></span>
                    </label>
                </div>
                <button class="btn btn-2">Отправить</button>
            </form>
        </section>
    </main>
    </body>
{% endblock %}

templates/core/everyweekreport.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body class="page-account">
    <input type="checkbox" id="hamb"/>
    {% include 'includes/header.html' %}
    <main>
        <section class="account">
            <h1>Еженедельный отчет</h1>
            <form class="account-form" enctype="multipart/form-data" method="post"
                  action="{% url 'core:everyweekreport' %}">
                {% csrf_token %}
                <div class="account-field">
                    <label for="date">Дата</label>
                    {{ form.date }}
                </div>
                <div class="account-field">
                    <label for="weight">Вес, кг</label>
                    <input type="number" name="weight" id="weight" step="0.1" min="0" required/>
                </div>
                <div class="account-field">
                    <label for="neck">Шея, см</label>
                    <input type="number" name="neck" id="neck" step="0.1" min="0" required/>
                </div>
                <div class="account-field">
                    <label for="waist">Талия, см</label>
                    <input type="number" name="hips" id="hips" step="0.1" min="0" required/>
                </div>
                <div class="account-field">
                    <label for="hips">Бёдра, см</label>
                    <input type="number" name="waist" id="waist" step="0.1" min="0" required/>
                </div>
                <div class="account-photo">
                    <p class="account-photo-title">Фото-отчет</p>
                    <div class="view">
                        <img src="{% static 'img/speredi.png' %}"/>
                        <div class="account-photo-field">
                            <input type="file" onchange="previewFile()" name="front_view" id="front_view"
                                   accept="image/png, image/jpeg">
                            <label for="front_view">
                                <span>Вид спереди</span>
                                <span class="sel">Выбрать</span>
                                <span class="img">
                    <img src="" height="73" alt="">
                  </span>

                            </label>

                        </div>
                    </div>
                    <div class="view">
                        <img src="{% static 'img/sboku.png' %}"/>
                        <div class="account-photo-field">
                            <input type="file" onchange="previewFile1()" name="side_view" id="side_view"
                                   accept="image/png, image/jpeg">
                            <label for="side_view">
                                <span>Вид сбоку</span>
                                <span class="sel">Выбрать</span>
                                <span class="img">
                    <img src="" height="73" alt="">
                  </span>
                            </label>
                        </div>
                    </div>
                    <div class="view">
                        <img src="{% static 'img/back.png' %}"/>
                        <div class="account-photo-field">
                            <input type="file" onchange="previewFile2()" name="back_view" id="back_view"
                                   accept="image/png, image/jpeg">
                            <label for="back_view">
                                <span>Вид сзади</span>
                                <span class="sel">Выбрать</span>
                                <span class="img">
                    <img src="" height="73" alt="">
                  </span>
                            </label>
                        </div>
                    </div>
                </div>
                <button class="btn btn-2">Отправить</button>
            </form>
        </section>
    </main>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script>

        function previewFile() {
            const preview = document.querySelector('label[for=front_view] img');
            const file = document.querySelector('input[name=front_view]').files[0];
            const span = document.querySelector('label[for=front_view] .sel');
            const reader = new FileReader();
            reader.addEventListener("load", function () {
                preview.src = reader.result;
            }, false);
            if (file) {
                reader.readAsDataURL(file);
                span.parentNode.removeChild(span);
            }
        }

        function previewFile1() {
            const preview = document.querySelector('label[for=side_view] img');
            const file = document.querySelector('input[name=side_view]').files[0];
            const span = document.querySelector('label[for=side_view] .sel');
            const reader = new FileReader();
            reader.addEventListener("load", function () {
                preview.src = reader.result;
            }, false);
            if (file) {
                reader.readAsDataURL(file);
                span.parentNode.removeChild(span);
            }
        }

        function previewFile2() {
            const preview = document.querySelector('label[for=back_view] img');
            const file = document.querySelector('input[name=back_view]').files[0];
            const span = document.querySelector('label[for=back_view] .sel');
            const reader = new FileReader();
            reader.addEventListener("load", function () {
                preview.src = reader.result;
            }, false);
            if (file) {
                reader.readAsDataURL(file);
                span.parentNode.removeChild(span);
            }
        }
    </script>
    </body>
{% endblock %}

templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <body class="page-reviews">
    <header>
        {% include 'includes/nav.html' %}
    </header>
    <main>
        <section class="reviews">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">
                            {{ message|safe }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
            <h1>Здесь вкусно худеют</h1>
            {% if not user.is_authenticated %}
                <a href="{% url 'users:signup' %}" class="btn">Записаться в проект</a>
            {% endif %}
            <!-- Slider main container -->
            <div class="swiper">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper">
                    <!-- Slides -->
                    {% for image in page.pageimage_set.all %}
                        <div class="slide swiper-slide">
                            <!-- <label for="s5"></label> -->
                            <div>
                                <p class="slide-title">До занятий</p>
                                <img src="{{ image.image_before.url }}"/>
                            </div>

                        </div>
                    {% endfor %}
                </div>
                <!-- If we need pagination -->
                <div class="swiper-pagination"></div>
            </div>
            <div class="reviews">
                {% for review in reviews %}
                    <div class="table1">
                        <p class="table1-title">{{ review.name }}</p>
                        <div class="table1-content">
                            <div class="t1-row">
                                {{ review.text|safe }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>


        </section>
    </main>
    <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
    <script src="https://unpkg.com/browse/swiper@8/modules/effect-coverflow/"></script>
    <script src="https://unpkg.com/browse/swiper@8/modules/pagination/pagination.js"></script>
    <script>
        var swiper = new Swiper(".swiper", {
            effect: "coverflow",
            grabCursor: true,
            centeredSlides: true,
            slidesPerView: "auto",
            coverflowEffect: {
                rotate: 50,
                stretch: 0,
                depth: 100,
                modifier: 1,
                slideShadows: true,
            },
            pagination: {
                el: ".swiper-pagination",
                clickable: true
            },
        });
        // function myFunction(event) {
        //   var x = event.touches[0].clientX;
        //   var y = event.touches[0].clientY;
        //   console.log(x, y);
        //   // document.getElementById("demo").innerHTML = x + ", " + y;
        // }
    </script>
    </body>
{% endblock %}

templates/core/success.html
{% extends 'base.html' %}

{% block content %}
    <body class="page-account">
    <input type="checkbox" id="hamb"/>
    {% include 'includes/header.html' %}
    <main>
        <section class="account sent">
            <h1>Отчет отправлен!</h1>

            <a href="{% url 'core:results' %}" class="btn">
                <span>Мой результат</span>
            </a>
        </section>
    </main>
    </body>
{% endblock %}