core/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from core.views import HomeView, EveryDayReportView, EveryWeekReportView, Results, AdminReview, Success, AboutPage, \
    AdminResultView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('everydayreport/', login_required(EveryDayReportView.as_view()), name='everydayreport'),
    path('everyweekreport/', login_required(EveryWeekReportView.as_view()), name='everyweekreport'),
    path('results/', login_required(Results.as_view()), name='results'),
    path('adminviewresults/<pk>/', login_required(AdminResultView.as_view()), name='results'),
    path('adminreview/', login_required(AdminReview.as_view()), name='admin_review'),
    path('success/', Success.as_view(), name='success'),
    path('about/', AboutPage.as_view(), name='about'),
]

fitnesstreker/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from fitnesstreker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("users.urls", namespace="users")),
    path('', include("core.urls", namespace="core")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import SignUp, ProfileUpdate, ProfileCreate

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(
        template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(
        template_name='users/logout.html'), name='logout'),
    path('profilecreate/', login_required(ProfileCreate.as_view()), name='profile_create'),
    path('profileupdate/', login_required(ProfileUpdate.as_view()), name='profile_update'),
]

templates/includes/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,user-scalable=no,viewport-fit=cover,shrink-to-fit=no">
    <title>Запись в проект</title>
    <meta name="description" content="">
    <link rel="icon" href="{% static 'favicon.svg' %}" type="image/svg+xml">
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/png">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Istok+Web:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="https://unpkg.com/browse/swiper@8/modules/pagination/pagination.min.css"/>
</head>

templates/includes/header.html
{% load static %}
<header>
    <nav>
        <div class="profile">
            <img src="{% static 'img/profile.svg' %}"/>
            {% if request.user.profile %}
            <a href="{% url 'users:profile_update' %}" class="name">{{ request.user.profile.name }}</a>
            {% else %}
                <a href="{% url 'users:profile_create' %}" class="name">Заполните профиль</a>
            {% endif %}
        </div>
        <label for="hamb">
            <span></span>
            <span></span>
            <span></span>
        </label>
        <div class="hamb">
            <a href="{% url 'core:everydayreport' %}" >Ежедневный отчет</a>
            <a href="{% url 'core:everyweekreport' %}">Еженедельный отчет</a>
            <a href="{% url 'core:results' %}">Мой результат</a>
            <a href="{% url 'core:admin_review' %}">Задания на неделю</a>
            <a href="{% url 'core:about' %}">О проекте</a>
            <a href="{% url 'users:logout' %}">Выйти</a>
            <label for="hamb"></label>
        </div>
    </nav>
</header>

templates/includes/nav.html
<nav>
    <a href="{% url 'core:about' %}">О проекте</a>
    <a href="/" class="active">Отзывы</a>
    {% if user.is_authenticated %}
        {% if user.profile.active %}
            <a href="{% url 'core:admin_review' %}">Профиль</a>
            <a href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'users:profile_update' %}">Профиль</a>
            <a href="{% url 'users:logout' %}">Выйти</a>
        {% endif %}
    {% else %}
        <a href="{% url 'users:login' %}" class="entry-a">Войти</a>
    {% endif %}
</nav>